### PR TITLE
arbirtrarily spaced bin grids

### PR DESCRIPTION
**Pull request by djerius**
This changeset adds the ability to specify arbitrarily spaced bin grids, using a binary search into the grid to get the index.

It is functionaly complete except for documentation, which I'll work on subsequent to any changes you'd like to make (I hate having to write documentation twice).  I plan on releasing a companion module Math::Histo::Grids to aid in generating more commonly used grids.

### CODE REVIEW

**Comment by ebaudrez** [comment]
Dear Diab

You must be kidding, right? You took a long-standing to-do item from my to-do list and implemented it while I was doing ... nothing :-)

Seriously, thank you for your contribution, much appreciated. Unfortunately I am leaving for a conference this weekend and will either be short of time or network access for a week.

Is it OK if I have a look at this after I return from the conference? Or do you need me to integrate this sooner? (Perhaps because you want to use this for your own work?) What I could do is merge it in a temporary branch and release a trial distribution on CPAN if you are not too keen on packing a dist yourself with Dist::Zilla.

Thank you again and best regards
Edward

**Comment by djerius** [comment]
Edward,

Glad to be of help! (And very glad you'd already authored this module, else I'd have started one on my own.  Nice not to have to do the work! Thanks)

No need for an immediate response.  Enjoy the conference.

**Comment by ebaudrez** [comment]
Dear Diab

I've just reviewed your changes. Looks good. I have a couple of comments:
- the documentation is still missing, but you know that
- there is no test on the supplied grid whether it is strictly monotonously increasing (or decreasing). In other places in the library, user-supplied arguments are checked for validity in order to prevent surprises, and I'd think this should be the case for the grid, too. What are your thoughts?
- you do test the new _flatten_into_grid routine, but only against _flatten_into (using sequence). I'd like to see a test where it is tested with a presupplied list of edges and against a known outcome. Having such a test is also useful as a sort of 'documentation' for people looking at the implementation.
- just a question: why did you change the test count in t/04-flatten.t from a fixed count to an undetermined count? As we expect both _flatten_into and _flatten_into_grid to be always available, I don't see a reason the test count can't be determined up front. Did I miss something?

That's all. Thank for your nice contribution, and I am looking forward to your changes or comments.

Edward

**Comment by djerius** [comment]
Edward,

Sorry for the long delay.  I've amended the code to (hopefully) address your concerns.  One major change was to split the pp directory into pp/Actions and pp/Utils, as I added  a pp routine to validate the grid and actions.pd isn't the logical place to put it.   At the moment I'm not sure how to get the PP build infrastructure to handle multiple .pd files in a single directory; creating the extra directory layer was the easiest approach.

No docs yet; let me know if this version works for you and I'll start on the docs.

Diab

**Comment by ebaudrez** [comment]
Thank you Diab! I'll have a look shortly!

**Comment by ebaudrez** [comment]
Ok, so I haven't reacted as 'shortly' as I would have liked, sorry. Your latest version looks good. Do you still feel like writing the documentation?

Looking forward to your response,
Edward

**Comment by djerius** [comment]
Edward,

No worries about the wait.  I'll set aside some time in the next couple of weeks to work on the documentation.

Diab

**Comment by djerius** [comment]
Edward,

Time flies when you're (not?) having fun.  

A couple of changes since our last conversation:
1. I've added some explicit checks to add_axis to ensure consistent bin specifications
2. I've finally added some documentation.

Thanks,

Diab

**Comment by ebaudrez** [comment]
Ok, I'll have a look. Thanks!

**Comment by ebaudrez** [comment]
Diab, thanks for the modifications! They look fine to me! (One minor remark is that even though I appreciate that you want to help me by rebasing and squashing your changes, it made it slightly harder to assess what had changed between the different versions you proposed. But your work is much appreciated!)

I can go ahead and merge this and push out a new release. Are you fine with that?

**Comment by djerius** [comment]
Please go ahead.  Sorry about the premature squash/rebasing!

**Comment by ebaudrez** [comment]
Merged and released. Thank you Diab! (And no worries about the squashing and rebasing.)

**Pull request merged**
