### PR TITLE
Use shared GitHub Actions

### PR DESCRIPTION
**Pull request by zmughal**
Connects with <https://github.com/PDLPorters/devops/pull/8>.

### CODE REVIEW

**Comment by mohawk2** [comment]
Looks great! Merge when you feel appropriate :-)

**Comment by mohawk2** [comment]
@ebaudrez Could you make @zmughal a collaborator on this repo as well? :-)

**Comment by ebaudrez** [comment]
> @ebaudrez Could you make @zmughal a collaborator on this repo as well? :-)

Should be OK now.

**Comment by mohawk2** [comment]
> > @ebaudrez Could you make @zmughal a collaborator on this repo as well? :-)
> 
> Should be OK now.

I'm still only seeing him here as "Contributor", are you sure?

**Comment by ebaudrez** [comment]
> > > @ebaudrez Could you make @zmughal a collaborator on this repo as well? :-)
> > 
> > 
> > Should be OK now.
> 
> I'm still only seeing him here as "Contributor", are you sure?

It's still awaiting his approval, I think.

**Comment by zmughal** [comment]
Ah, sorry about that. I wish that GitHub invites were prominent on the website instead of digging around in my e-mail.

**Comment by mohawk2** [comment]
Thank you both of you! Could I ask you each to look at the changes I made yesterday? This distro was broken under 2.072 which newly has `null` ndarrays with a NULL data pointer. This means that until then, this library was working by coincidence with `null` having a single uninitialised value in its `data`, so it sort of worked. I have now made `null` objects be replaced by `zeroes` objects, but I am not sure it is correct (and as I write this am thinking they should instead be size 1, to get automatically dummied up).

**Comment by ebaudrez** [comment]
Hi Ed, sorry but I won't be much help here, it's been a long time I've used the software myself, and I don't quite understand the change you made (or even the problem you're trying to solve). I don't have the resources to look into it now. So you are free to do what you think is best. (But I'd like to take this opportunity to thank you both, Zaki and Ed, for taking care of this software!)

**Comment by mohawk2** [comment]
You are most welcome!

For posterity: nulls were never a good idea to allow/encourage as inputs, and the recent change in PDL forbids them; replacing them with `zeroes` ndarrays makes the tests pass, so assuming the tests capture all required behaviour, all is well!

**Comment by ebaudrez** [comment]
> For posterity: nulls were never a good idea to allow/encourage as inputs, and the recent change in PDL forbids them; replacing them with `zeroes` ndarrays makes the tests pass, so assuming the tests capture all required behaviour, all is well!

Thank you for clarifying that! Yes, I am OK with that. Kind regards!

**Pull request merged**
